server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://victorb:1234abcd@cluster0.x9cw1.mongodb.net/SA590-FinalProject?retryWrites=true&w=majority
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/